"use client";
import type { Metadata } from 'next';
import { Inter, Lato } from 'next/font/google';
import { CssBaseline, ThemeProvider } from "@mui/material";
import { ColorModeContext, useMode } from '@/theme';
import '../styles/globals.scss';
import '../styles/home.scss';
import '../styles/navbar.scss';
import NavBar from '@/components/NavBar';

// const inter = Inter({ subsets: ['latin'] });

const lato = Lato({ 
  style: ['normal'],
  weight: ['400', '700', '900'], 
  subsets: ['latin'] 
})

// export const metadata: Metadata = {
//   title: 'Lexy Store',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [theme, colorMode] = useMode();
  return (
    <html lang="en">
      <body className={lato.className} style={{ minHeight: '100vh', padding: '0px' }}>
        <ColorModeContext.Provider value={colorMode}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <NavBar />
            {children}
          </ThemeProvider>
        </ColorModeContext.Provider>
      </body>
    </html>
  )
}
